use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::io::Result;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct IncludeEntry {
    pub file_name: String,
    pub package: String,
}

struct ModuleNode {
    files: Vec<String>,
    children: BTreeMap<String, ModuleNode>,
}

struct RenderOptions {
    include_from_out_dir_env: bool,
    absolute_out_dir: Option<PathBuf>,
}

impl RenderOptions {
    fn include_expr(&self, file_name: &str) -> String {
        if self.include_from_out_dir_env {
            return format!("concat!(env!(\"OUT_DIR\"), \"/{file_name}\")");
        }

        let out_dir = self
            .absolute_out_dir
            .as_ref()
            .expect("absolute_out_dir must be set when include_from_out_dir_env is false");
        let full_path = out_dir.join(file_name);
        format!("{:?}", full_path.to_string_lossy())
    }
}

impl ModuleNode {
    fn new() -> Self {
        Self {
            files: Vec::new(),
            children: BTreeMap::new(),
        }
    }

    fn insert_include(&mut self, segments: &[&str], file_name: &str) {
        if segments.is_empty() {
            self.files.push(file_name.to_string());
            return;
        }

        let child = self
            .children
            .entry(segments[0].to_string())
            .or_insert_with(ModuleNode::new);
        child.insert_include(&segments[1..], file_name);
    }

    fn render_contents(&self, out: &mut String, depth: usize, options: &RenderOptions) {
        let indent = "    ".repeat(depth);

        for file_name in &self.files {
            writeln!(
                out,
                "{indent}include!({});",
                options.include_expr(file_name)
            )
            .unwrap();
        }

        for (name, child) in &self.children {
            let escaped = escape_mod_name(name);
            writeln!(out, "{indent}pub mod {escaped} {{").unwrap();
            child.render_contents(out, depth + 1, options);
            writeln!(out, "{indent}}}").unwrap();
        }
    }
}

fn escape_mod_name(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn", "gen", "abstract", "become", "box", "do",
        "final", "macro", "override", "priv", "try", "typeof", "unsized", "virtual", "yield",
    ];

    if KEYWORDS.contains(&name) {
        if matches!(name, "self" | "super" | "Self" | "crate") {
            format!("{name}_")
        } else {
            format!("r#{name}")
        }
    } else {
        name.to_string()
    }
}

pub(crate) fn generate(
    include_file_name: &str,
    out_dir: &str,
    entries: &[IncludeEntry],
    include_from_out_dir_env: bool,
) -> Result<()> {
    let out_path = Path::new(out_dir);
    let absolute_out_dir = if include_from_out_dir_env {
        None
    } else {
        Some(std::fs::canonicalize(out_path)?)
    };
    let render_options = RenderOptions {
        include_from_out_dir_env,
        absolute_out_dir,
    };

    let mut root = ModuleNode::new();

    for entry in entries {
        let segments: Vec<&str> = if entry.package.is_empty() {
            Vec::new()
        } else {
            entry.package.split('.').collect()
        };
        root.insert_include(&segments, &entry.file_name);
    }

    let mut output = String::from("// @generated by tonic-buffa-build\n");
    root.render_contents(&mut output, 0, &render_options);

    let include_path = out_path.join(include_file_name);
    std::fs::write(include_path, output)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn setup_dir(files: &[&str]) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        for f in files {
            fs::write(dir.path().join(f), "// generated").unwrap();
        }
        dir
    }

    #[test]
    fn renders_nested_modules() {
        let dir = setup_dir(&["hello.rs", "foo.bar.rs"]);
        let entries = vec![
            IncludeEntry {
                file_name: "hello.rs".to_string(),
                package: "hello".to_string(),
            },
            IncludeEntry {
                file_name: "foo.bar.rs".to_string(),
                package: "foo.bar".to_string(),
            },
        ];

        generate("mod.rs", dir.path().to_str().unwrap(), &entries, true).unwrap();

        let content = fs::read_to_string(dir.path().join("mod.rs")).unwrap();
        assert!(content.contains("pub mod hello {"));
        assert!(content.contains("pub mod foo {"));
        assert!(content.contains("pub mod bar {"));
        assert!(content.contains(r#"include!(concat!(env!("OUT_DIR"), "/hello.rs"));"#));
        assert!(content.contains(r#"include!(concat!(env!("OUT_DIR"), "/foo.bar.rs"));"#));
    }
}
