use std::collections::BTreeMap;
use std::fmt::Write as FmtWrite;
use std::io::Result;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct IncludeEntry {
    pub file_name: String,
    pub package: String,
}

struct ModuleNode {
    files: Vec<String>,
    reexport: Option<String>,
    children: BTreeMap<String, ModuleNode>,
}

struct RenderOptions {
    include_from_out_dir_env: bool,
    absolute_out_dir: Option<PathBuf>,
}

impl RenderOptions {
    fn include_expr(&self, file_name: &str) -> String {
        if self.include_from_out_dir_env {
            return format!("concat!(env!(\"OUT_DIR\"), \"/{file_name}\")");
        }

        let out_dir = self
            .absolute_out_dir
            .as_ref()
            .expect("absolute_out_dir must be set when include_from_out_dir_env is false");
        let full_path = out_dir.join(file_name);
        format!("{:?}", full_path.to_string_lossy())
    }
}

impl ModuleNode {
    fn new() -> Self {
        Self {
            files: Vec::new(),
            reexport: None,
            children: BTreeMap::new(),
        }
    }

    fn insert_include(&mut self, segments: &[&str], file_name: &str) {
        if segments.is_empty() {
            self.files.push(file_name.to_string());
            return;
        }

        let child = self
            .children
            .entry(segments[0].to_string())
            .or_insert_with(ModuleNode::new);
        child.insert_include(&segments[1..], file_name);
    }

    fn insert_reexport(&mut self, segments: &[&str], reexport_path: &str) {
        if segments.is_empty() {
            self.reexport = Some(reexport_path.to_string());
            return;
        }

        let child = self
            .children
            .entry(segments[0].to_string())
            .or_insert_with(ModuleNode::new);
        child.insert_reexport(&segments[1..], reexport_path);
    }

    fn render_contents(&self, out: &mut String, depth: usize, options: &RenderOptions) {
        let indent = "    ".repeat(depth);

        if let Some(ref reexport) = self.reexport {
            writeln!(out, "{indent}pub use {reexport}::*;").unwrap();
        }

        for file_name in &self.files {
            writeln!(
                out,
                "{indent}include!({});",
                options.include_expr(file_name)
            )
            .unwrap();
        }

        for (name, child) in &self.children {
            let escaped = escape_mod_name(name);
            writeln!(out, "{indent}pub mod {escaped} {{").unwrap();
            child.render_contents(out, depth + 1, options);
            writeln!(out, "{indent}}}").unwrap();
        }
    }
}

fn escape_mod_name(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
        "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
        "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
        "use", "where", "while", "async", "await", "dyn", "gen", "abstract", "become", "box", "do",
        "final", "macro", "override", "priv", "try", "typeof", "unsized", "virtual", "yield",
    ];

    if KEYWORDS.contains(&name) {
        if matches!(name, "self" | "super" | "Self" | "crate") {
            format!("{name}_")
        } else {
            format!("r#{name}")
        }
    } else {
        name.to_string()
    }
}

pub(crate) fn generate(
    include_file_name: &str,
    out_dir: &str,
    entries: &[IncludeEntry],
    extern_reexports: &[(String, String)],
    include_from_out_dir_env: bool,
) -> Result<()> {
    let out_path = Path::new(out_dir);
    let absolute_out_dir = if include_from_out_dir_env {
        None
    } else {
        Some(std::fs::canonicalize(out_path)?)
    };
    let render_options = RenderOptions {
        include_from_out_dir_env,
        absolute_out_dir,
    };

    let mut root = ModuleNode::new();

    for entry in entries {
        let segments: Vec<&str> = if entry.package.is_empty() {
            Vec::new()
        } else {
            entry.package.split('.').collect()
        };
        root.insert_include(&segments, &entry.file_name);
    }

    for (proto_path, rust_path) in extern_reexports {
        let segments: Vec<&str> = if proto_path.is_empty() {
            Vec::new()
        } else {
            proto_path.split('.').collect()
        };
        root.insert_reexport(&segments, rust_path);
    }

    let mut output = String::from("// @generated by connectrpc-axum-build\n");
    root.render_contents(&mut output, 0, &render_options);

    let include_path = out_path.join(include_file_name);
    std::fs::write(include_path, output)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn setup_dir(files: &[&str]) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        for f in files {
            fs::write(dir.path().join(f), "// generated").unwrap();
        }
        dir
    }

    #[test]
    fn single_level_packages() {
        let dir = setup_dir(&["hello.rs", "echo.rs"]);
        let entries = vec![
            IncludeEntry {
                file_name: "echo.rs".to_string(),
                package: "echo".to_string(),
            },
            IncludeEntry {
                file_name: "hello.rs".to_string(),
                package: "hello".to_string(),
            },
        ];
        generate(
            "protos.rs",
            dir.path().to_str().unwrap(),
            &entries,
            &[],
            true,
        )
        .unwrap();
        let content = fs::read_to_string(dir.path().join("protos.rs")).unwrap();
        assert!(content.contains("pub mod echo {"));
        assert!(content.contains("pub mod hello {"));
        assert!(content.contains(r#"include!(concat!(env!("OUT_DIR"), "/echo.rs"));"#));
        assert!(content.contains(r#"include!(concat!(env!("OUT_DIR"), "/hello.rs"));"#));
    }

    #[test]
    fn multiple_files_same_package_preserve_order() {
        let dir = setup_dir(&["hello.rs", "hello.connect.rs", "hello.tonic.rs"]);
        let entries = vec![
            IncludeEntry {
                file_name: "hello.rs".to_string(),
                package: "hello".to_string(),
            },
            IncludeEntry {
                file_name: "hello.connect.rs".to_string(),
                package: "hello".to_string(),
            },
            IncludeEntry {
                file_name: "hello.tonic.rs".to_string(),
                package: "hello".to_string(),
            },
        ];
        generate(
            "protos.rs",
            dir.path().to_str().unwrap(),
            &entries,
            &[],
            true,
        )
        .unwrap();
        let content = fs::read_to_string(dir.path().join("protos.rs")).unwrap();
        let hello_idx = content.find("/hello.rs").unwrap();
        let connect_idx = content.find("/hello.connect.rs").unwrap();
        let tonic_idx = content.find("/hello.tonic.rs").unwrap();
        assert!(hello_idx < connect_idx);
        assert!(connect_idx < tonic_idx);
    }

    #[test]
    fn multi_level_package() {
        let dir = setup_dir(&["buf.validate.rs"]);
        let entries = vec![IncludeEntry {
            file_name: "buf.validate.rs".to_string(),
            package: "buf.validate".to_string(),
        }];
        generate(
            "protos.rs",
            dir.path().to_str().unwrap(),
            &entries,
            &[],
            true,
        )
        .unwrap();
        let content = fs::read_to_string(dir.path().join("protos.rs")).unwrap();
        assert!(content.contains("pub mod buf {"));
        assert!(content.contains("pub mod validate {"));
        assert!(content.contains(r#"include!(concat!(env!("OUT_DIR"), "/buf.validate.rs"));"#));
    }

    #[test]
    fn root_package_files_render_at_root() {
        let dir = setup_dir(&["root.rs"]);
        let entries = vec![IncludeEntry {
            file_name: "root.rs".to_string(),
            package: String::new(),
        }];
        generate(
            "protos.rs",
            dir.path().to_str().unwrap(),
            &entries,
            &[],
            true,
        )
        .unwrap();
        let content = fs::read_to_string(dir.path().join("protos.rs")).unwrap();
        assert!(content.contains(r#"include!(concat!(env!("OUT_DIR"), "/root.rs"));"#));
        assert!(!content.contains("pub mod root {"));
    }

    #[test]
    fn extern_reexport_google_protobuf() {
        let dir = setup_dir(&["cerberus.v1.rs"]);
        let entries = vec![IncludeEntry {
            file_name: "cerberus.v1.rs".to_string(),
            package: "cerberus.v1".to_string(),
        }];
        let reexports = vec![(
            "google.protobuf".to_string(),
            "::buffa_types::google::protobuf".to_string(),
        )];
        generate(
            "protos.rs",
            dir.path().to_str().unwrap(),
            &entries,
            &reexports,
            true,
        )
        .unwrap();
        let content = fs::read_to_string(dir.path().join("protos.rs")).unwrap();
        assert!(content.contains("pub mod google {"));
        assert!(content.contains("pub mod protobuf {"));
        assert!(content.contains("pub use ::buffa_types::google::protobuf::*;"));
        assert!(content.contains("pub mod cerberus {"));
    }
}
